name: api-arkham-build
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "8686:8686"
    environment:
      NODE_ENV: development
      PORT: 8686
      POSTGRES_URL: postgresql://postgres:postgres@db:5432/api-arkham-build
      CORS_ORIGINS: http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: api-arkham-build
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: