name: api-arkham-build

services:
  app:
    build:
      context: .
      target: development
    ports:
      - "8686:8686"
    env_file: .env
    volumes:
      - ./src:/app/src
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10

  migrate:
    build:
      context: .
      target: dbmate
    env_file: .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable
    volumes:
      - ./src/db:/db
    depends_on:
      db:
        condition: service_healthy
    command: up

volumes:
  postgres_data:
