name: api-arkham-build

services:
  app:
    build:
      context: .
      target: development
    # Uncomment for memory profiling
    # command: npm run inspect
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8686:8686"
      - "9229:9229"
    volumes:
      - ./src:/app/src

  # cron:
  #   build:
  #     context: .
  #     target: development
  #   command: sh -c "(env && cat config/crontab) | crontab - && crond -f"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   env_file: .env
  #   volumes:
  #     - ./src:/app/src

  db:
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 1s
      retries: 10
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
