type: http_request
model: http_request
id: rq_sDDtwQeKjE
createdAt: 2025-07-30T21:51:13.618760
updatedAt: 2025-08-02T23:33:59.124252
workspaceId: wk_bBoraEVHnK
folderId: fl_ZDDpsyiw3d
authentication: {}
authenticationType: null
body:
  text: |-
    {
      "required_cards": ["", "01093"]
    }
bodyType: application/json
description: ''
headers:
- enabled: true
  name: Content-Type
  value: application/json
  id: ehIAYH35yh
method: GET
name: absolute_rank, required cards
sortPriority: 1000.0
url: ${[ base_url ]}/v2/public/recommendations/03006-03006
urlParameters:
- enabled: true
  name: card
  value: '01088'
  id: rbGMCU5e2g
- enabled: true
  name: card
  value: '01093'
  id: F2iFt3XB97
- enabled: false
  name: ''
  value: ''
  id: BT68pagR4v
- enabled: true
  name: ''
  value: ''
  id: P9hGgvu7Zr
