type: folder
model: folder
id: fl_JK7iKL4dYC
createdAt: 2025-08-02T23:35:19.907711
updatedAt: 2025-08-03T09:30:12.731419
workspaceId: wk_bBoraEVHnK
folderId: null
authentication: {}
authenticationType: null
description: ''
headers: []
name: Decklists Search
sortPriority: -1754177700000.0
