type: http_request
model: http_request
id: rq_nHydwSzT3x
createdAt: 2025-08-03T09:45:25.391281
updatedAt: 2025-08-03T16:57:26.270669
workspaceId: wk_bBoraEVHnK
folderId: fl_JK7iKL4dYC
authentication: {}
authenticationType: null
body: {}
bodyType: null
description: ''
headers: []
method: GET
name: Sort by popularity (default)
sortPriority: 9000.0
url: ${[ base_url ]}/v2/public/arkhamdb-decklists/search
urlParameters:
- enabled: false
  name: ''
  value: ''
  id: dcGbiQUu2x
- enabled: true
  name: ''
  value: ''
  id: 89gyVcWvPm
