type: http_request
model: http_request
id: rq_nHydwSzT3x
createdAt: 2025-08-03T09:45:25.391281
updatedAt: 2025-08-03T11:31:45.789100
workspaceId: wk_bBoraEVHnK
folderId: fl_JK7iKL4dYC
authentication: {}
authenticationType: null
body: {}
bodyType: null
description: ''
headers: []
method: GET
name: No parameters
sortPriority: 0.0
url: ${[ base_url ]}/v2/public/decklists-search
urlParameters:
- enabled: false
  name: ''
  value: ''
  id: 2p47UJBZc6
- enabled: true
  name: ''
  value: ''
  id: YRueNcAqXI
