type: http_request
model: http_request
id: rq_vAfbS4PzjA
createdAt: 2025-07-30T19:39:22.590474
updatedAt: 2025-08-02T23:33:59.128801
workspaceId: wk_bBoraEVHnK
folderId: fl_ZDDpsyiw3d
authentication: {}
authenticationType: null
body:
  text: |-
    {
      "canonical_investigator_code": "03006-03006",
      "analysis_algorithm": "percentile_rank"
      }
bodyType: application/json
description: ''
headers:
- enabled: true
  name: Content-Type
  value: application/json
  id: ehIAYH35yh
method: GET
name: percentile_rank
sortPriority: 3000.0
url: ${[ base_url ]}/v2/public/recommendations/03006-03006
urlParameters:
- enabled: true
  name: algo
  value: percentile_rank
  id: 5U8j8pCfJJ
- enabled: true
  name: ''
  value: ''
  id: sNmA2TCsIA
