type: folder
model: folder
id: fl_ZDDpsyiw3d
createdAt: 2025-07-26T11:35:36.516054
updatedAt: 2025-08-02T17:17:32.623725
workspaceId: wk_bBoraEVHnK
folderId: null
authentication: {}
authenticationType: null
description: ''
headers: []
name: Recommendations
sortPriority: 1000.0
