type: http_request
model: http_request
id: rq_4dGrr6wgMh
createdAt: 2025-08-03T09:53:11.406169
updatedAt: 2025-08-03T12:31:37.554613
workspaceId: wk_bBoraEVHnK
folderId: fl_JK7iKL4dYC
authentication: {}
authenticationType: null
body: {}
bodyType: null
description: ''
headers: []
method: GET
name: Required cards
sortPriority: 2000.0
url: ${[ base_url ]}/v2/public/decklists-search
urlParameters:
- enabled: true
  name: card
  value: '01088'
  id: R8m37g00S6
- enabled: true
  name: ''
  value: ''
  id: 4FDpD3DZr2
