type: folder
model: folder
id: fl_eohufYAbAh
createdAt: 2025-08-05T11:00:48.407477
updatedAt: 2025-08-05T11:00:48.407478
workspaceId: wk_bBoraEVHnK
folderId: null
authentication: {}
authenticationType: null
description: ''
headers: []
name: Decklists Meta
sortPriority: -1754391600000.0
