type: folder
model: folder
id: fl_WSoGd3Tv2j
createdAt: 2025-08-02T23:34:48.939449
updatedAt: 2025-08-03T14:57:23.142328
workspaceId: wk_bBoraEVHnK
folderId: null
authentication: {}
authenticationType: null
description: ''
headers: []
name: Utils
sortPriority: 3000.0
