type: http_request
model: http_request
id: rq_cEn69FZRpw
createdAt: 2025-08-02T23:24:07.114533
updatedAt: 2025-08-02T23:33:59.127244
workspaceId: wk_bBoraEVHnK
folderId: fl_ZDDpsyiw3d
authentication: {}
authenticationType: null
body:
  text: |-
    {
      "canonical_investigator_code": "03006-03006"
    }
bodyType: null
description: ''
headers: []
method: GET
name: analyze_side_decks = false
sortPriority: 2000.0
url: ${[ base_url ]}/v2/public/recommendations/03006-03006
urlParameters:
- enabled: true
  name: analyze_side_decks
  value: 'false'
  id: tb9SsmKDxv
- enabled: true
  name: ''
  value: ''
  id: 6k0KJ6d2Ut
