type: http_request
model: http_request
id: rq_yEjFPaHqxW
createdAt: 2025-08-03T16:42:47.961796
updatedAt: 2025-08-03T16:44:16.216923
workspaceId: wk_bBoraEVHnK
folderId: fl_JK7iKL4dYC
authentication: {}
authenticationType: null
body: {}
bodyType: null
description: ''
headers: []
method: GET
name: Deck name
sortPriority: 1750.0
url: ${[ base_url ]}/v2/public/arkhamdb-decklists/search
urlParameters:
- enabled: true
  name: name
  value: hunt for previews
  id: Zv3r3rPUpb
- enabled: true
  name: ''
  value: ''
  id: Rpy0EWEAdd
