type: folder
model: folder
id: fl_WSoGd3Tv2j
createdAt: 2025-08-02T23:34:48.939449
updatedAt: 2025-08-04T13:55:48.797054
workspaceId: wk_bBoraEVHnK
folderId: null
authentication: {}
authenticationType: null
description: ''
headers: []
name: Misc.
sortPriority: 3000.0
